name: Ktlint Check

on:
  pull_request:
    branches:
      - '*'  # This applies to any branch for PRs
    paths:
      - '**/*.kt'
      - '**/*.kts'

  push:
    branches:
      - '*'  # This applies to any branch for pushes
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Cache Gradle dependencies (with updated cache key)
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.kts', '**/*.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck --continue