name: Ktlint Check

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '**/*.kt'
      - '**/*.kts'

  push:
    branches:
      - '*'
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts', '**/*.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck --continue