name: Ktlint Check

on:
  pull_request:
    branches:
      - '*'  # Trigger for any pull request targeting any branch
    paths:
      - '**/*.kt'
      - '**/*.kts'

  push:
    branches:
      - '*'  # Trigger for any push to any branch
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.kts', '**/*.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck --continue
